const ERRORS = {
  ERROR: 'ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR'
};

const ACCOUNT = {
  REGISTER_USER: 'REGISTER_USER',
  SIGN_IN_USER: 'SIGN_IN_USER',
  SIGN_OUT_USER: "SIGN_OUT_USER"
};

const ALERT = {
  HIDE_MESSAGE: 'HIDE_MESSAGE'
}

const POST = {
  LOAD: 'LOAD_POST',
  SAVE: 'SAVE_POST',
  EDIT: 'EDIT_POST',
  DELETE: 'DELETE_POST'
}

export { ERRORS, ACCOUNT, ALERT, POST}