const ERRORS = {
  ERROR: 'ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR'
};

const ACCOUNT = {
  REGISTER_USER: 'REGISTER_USER',
  SIGN_IN_USER: 'SIGN_IN_USER'
};

const ALERT = {
  SHOW_MESSAGE: 'SHOW_MESSAGE'
}

const POST = {
  LOAD: 'LOAD_POST',
  SAVE: 'SAVE_POST'
}

export { ERRORS, ACCOUNT, ALERT, POST}